services:

  postgres:
    image: postgres:latest
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurantmanagement_db
    ports:
      - "6723:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: